### ISSUE TITLE
Team 8 Review - VnV Plan - SRS Verification Plan Checklist

### ISSUE THREAD

**Issue by ShrillP** [MichaelBreau/nlp-mentalhealth#100]
I think the things your team has mentioned in the checklist for verifying your SRS are good and cover most of the important aspects of the SRS. However, I think that your team need to add one more thing to this checklist which is to ensure that all of your requirements are NAV (necessary, attainable, and verifiable). This is very important aspect to verifying your SRS because if not done, you may run the risk of experiencing delays with your project (may be due to the infeasibility of some of your requirements) and performance pitfalls. So I think it would be greatly beneficial to review all of your requirements outlined in your SRS and ensure they are necessary, attainable, and verifiable so that your team does not have any requirements that may not belong and can focus on what the absolute necessary requirements of the system are within the timeframe of the capstone project (some requirements may be _nice to have_ or may enhance your project, but should only be done if time permits).

**Comment by MichaelBreau** [comment]
Done.
