### ISSUE TITLE
Team 8 Review - VnV - Relevant Documentation

### ISSUE THREAD

**Issue by MohamedAly8** [MichaelBreau/nlp-mentalhealth#105]
![Screenshot 2023-11-06 at 5 57 28 PM](https://github.com/MichaelBreau/nlp-mentalhealth/assets/69180195/ba03b319-13a1-4ee7-b6a8-f92072fd8afb)

As part of relevant documentation, McMaster AI Guidelines were mentioned in the context of Generative AI.

From my understanding, I don't think Generative AI is relevant to the project. I think if worded differently it could be indeed a very relevant document to the project.

**Comment by benChinnery** [comment]
Section was changed to address McMaster's general AI policies and stances
