### ISSUE TITLE
Team 8 Review - VnV - Design Verification Plan

### ISSUE THREAD

**Issue by MohamedAly8** [MichaelBreau/nlp-mentalhealth#106]
![Screenshot 2023-11-06 at 5 59 20 PM](https://github.com/MichaelBreau/nlp-mentalhealth/assets/69180195/2d8e6efe-a8d9-4ae9-a7fc-8448e42ebe0e)

There are inconsistencies with pronoun usage that I have noticed throughout the document. I think it would be more formal if the document was in third person.

**Comment by benChinnery** [comment]
Issues has been started, considered low priority as most noticeable cases have now been accounted for

**Comment by MichaelBreau** [comment]
Done.
