### ISSUE TITLE
Team 8 Review SRS: MG Modules

### ISSUE THREAD

**Issue by MohamedAly8** [MichaelBreau/nlp-mentalhealth#146]
## Red Underlines:
There seems to be inconsistency in the format of the `Implemented By:` as below these modules (8.3), it's you team name, and in the provided screenshot below it is both .py files as well as Module Files. I think I understand that there is a dependency tree, but maybe you can use Module Files as a convention for all

## Green Underline:
I don't think that the input file format is a secret since it is external to the module, perhaps how the algorithm on how the input file is parsed is the secret?

## Purple Underline
Missing Module Label, I suspect it is a small LaTeX bug

![Screenshot 2024-01-19 at 5 27 55 PM](https://github.com/MichaelBreau/nlp-mentalhealth/assets/69180195/2fff5c66-c7d8-4195-b896-bb6c3511988e)

Team 8 TA: @Lyuyang0130

**Comment by benChinnery** [comment]
Fixed, through branch git-issues-fixes-ben
