### ISSUE TITLE
Team 8 Review - Missing exceptions and parameters for Exported Access Programs in MIS

### ISSUE THREAD

**Issue by rylan04** [MichaelBreau/nlp-mentalhealth#151]
In the screenshots below it shows that there are no possible exceptions. And for the majority of the access programs in the MIS there are no exceptions listed. It's possible there there may be uncaught built-in Python exceptions raised from code which need to be accounted for. For example, the write_file access program could raise an IO error.
![image](https://github.com/MichaelBreau/nlp-mentalhealth/assets/58240299/d9d78864-e0ca-4d13-bd61-e57259b6c8c9)
![image](https://github.com/MichaelBreau/nlp-mentalhealth/assets/58240299/3a0a33f8-d930-4d44-9735-c35b853c9e2a)
![image](https://github.com/MichaelBreau/nlp-mentalhealth/assets/58240299/9f7c41a3-4e96-416a-aa5b-d672187a9c61)

Additionally, there is inconsistency in the inclusion of parameters of your access programs such as the ones below missing despite having input and output variables defined in the Syntax section 

![image](https://github.com/MichaelBreau/nlp-mentalhealth/assets/58240299/23cb0e94-a1b9-47af-a440-dba6d7785834)

Below is an example which does include it

![image](https://github.com/MichaelBreau/nlp-mentalhealth/assets/58240299/95c507ab-0d88-4aa4-a259-6610f7a415e8)

Team 8 TA: @Lyuyang0130

**Comment by FranklinT668** [comment]
fixed during modularization process
