### ISSUE TITLE
Team 8 Review - VnV Report - Validation Beyond Testing

### ISSUE THREAD

**Issue by ShrillP** [MichaelBreau/nlp-mentalhealth#194]
I think it may be worthwhile to add a section to your VnV report that talks about in what ways, other than programmatic testing (e.g. unit testing), can your code and models be validated. For example, your code can be validated through code walkthroughs and reviews with Dr.Mosser and/or the NLP researchers. I think adding this section will not help to strengthen your report, but also will aid in achieving a higher confidence in your systems as well.

Team 8 TA: @Lyuyang0130

**Comment by MatthewCurtis4** [comment]
This would be nice to have but it does not seem to fit nicely in any of the sections we have and would not warrant its own section. This idea is also touched upon in other documents.
