### ISSUE TITLE
Team 8 Review - VnV Report - automated testing improvements

### ISSUE THREAD

**Issue by yili-liu** [MichaelBreau/nlp-mentalhealth#197]
![image](https://github.com/MichaelBreau/nlp-mentalhealth/assets/30164301/976b9cf9-a860-4056-8ad4-9e725c137ede)

I think you can expand on what you test as part of your automated testing suite, given that it is within your scope of the project.
for instance, you can use flake8 or another linter to better style your .py source code files.
another helpful tool is the use of github actions, which is a CI/CD service built into github which allows for building, testing, and deploying your software with ease.

**Comment by MatthewCurtis4** [comment]
Added in a part about our linter and GitHub actions.
