### ISSUE TITLE
Section S.1 Components "Prediction Component" says 'Gambling Addiction' when its not the only application and should be generalized (SRS Feedback Team 8 - Rylan)

### ISSUE THREAD

**Issue by rylan04** [MichaelBreau/nlp-mentalhealth#56]
This component specifically states 'Gambling Addiction' when there are more applications as per the eRisk competition. Also, the rubric states there should be no design decisions (i.e. "What not how"), so it may be better to generalize the component

**Comment by MichaelBreau** [comment]
Removed mention of gambling and generalized it.
