### ISSUE TITLE
Team 8 Review - SRS Section G.2 Current Situation - Explain Past eRisk Competitions

### ISSUE THREAD

**Issue by ShrillP** [MichaelBreau/nlp-mentalhealth#57]
According to the Meyers template for the SRS, section G.2 should explains the current situation and what can be improved on the existing system. I think that you have explained the current situation well. However, I think it might be beneficial and important to discuss the past NLP research. This may give you a better idea of the current situation (as of the most recent competition) and what their NLP model did and fell short of last year (I will link these research papers below). The research papers also discuss what they can improve on in terms of the NLP model which can be good to add within this section. What I have highlighted in red in the below screenshot, I think, is a good high-level goal, however I think here you can talk about the NLP team's research and their findings from previous competitions and research. I really thought talking about eRisk (highlighted in yellow) was nice and needed to provide some context.

![Screenshot 2023-10-08 at 4 34 09 PM](https://github.com/MichaelBreau/nlp-mentalhealth/assets/36174319/0e22d968-025f-449a-ae8e-d7a0bd14c8a7)

 NLP Past Research Papers:
- 2022: https://ceur-ws.org/Vol-3180/paper-74.pdf
- 2021: https://ceur-ws.org/Vol-2936/paper-83.pdf
- 2020: https://ceur-ws.org/Vol-2696/paper_53.pdf
- 2018: https://ceur-ws.org/Vol-2125/paper_173.pdf
- 2017: https://ceur-ws.org/Vol-1866/paper_127.pdf

**Comment by ShrillP** [comment]
This issue was created by Team 8, tagging our marking TA as recommended by Professor Smith @Lyuyang0130

**Comment by MichaelBreau** [comment]
Added information.
