### ISSUE TITLE
Team 8 Review Functional Req: Lack of Specificity in Tokenization Process

### ISSUE THREAD

**Issue by MohamedAly8** [MichaelBreau/nlp-mentalhealth#60]
The functional requirement states, "The system will divide text into individual units of words and or sub-words (Tokenization)." This requirement is a bit ambiguous in terms of what constitutes a "sub-word." In the realm of NLP, tokenization can be intricate, with various methods like word-based, morpheme-based, or even byte-pair encoding.

![Screenshot 2023-10-08 at 7 58 29 PM](https://github.com/MichaelBreau/nlp-mentalhealth/assets/69180195/2c26077e-f00a-41af-86ab-38e24798cfa7)

Suggestion:  Clarify the tokenization process. Define what "sub-words" mean in the context of the system or specify the tokenization technique that will be used.

**Comment by MichaelBreau** [comment]
I believe this would probably intrude into a design specification so keeping it general here might be better. We did update this section to be clear on word definitions however.
