### ISSUE TITLE
Team 8 Review - Section S.6 Verification & Acceptance Criteria - Adding Regression & Integration Testing for Pipeline

### ISSUE THREAD

**Issue by ShrillP** [MichaelBreau/nlp-mentalhealth#63]
When discussing how your team is going to test the data processing pipeline part of your system, only unit testing was mentioned. Pipelines are usually made up of smaller, more atomic units which work together to make up a pipeline. So I was thinking maybe it would also be beneficial to test the data processing pipeline part of your system using regression and integration tests as well. This will also test if adding new pipeline components affects the existing pipeline (which may help reduce system complexity). The following resource is a good introduction to testing data pipelines: https://www.datafold.com/blog/testing-data-pipelines#testing-data-integrations.

![Screenshot 2023-10-08 at 9 37 07 PM](https://github.com/MichaelBreau/nlp-mentalhealth/assets/36174319/3e680f70-f921-4833-ba66-1675a4fa2431)

**Comment by MichaelBreau** [comment]
VnV plan went more in depth on our testing so I believe it should be fine to keep this general.
