### ISSUE TITLE
Team 8 Review - SR7/SR8 similarities

### ISSUE THREAD

**Issue by MohamedAly8** [MichaelBreau/nlp-mentalhealth#83]
![Screenshot 2023-10-23 at 7 34 19 PM](https://github.com/MichaelBreau/nlp-mentalhealth/assets/69180195/fe47d71f-8e97-4fb2-bb1b-0f594af3a438)

If the system can only operate on verified data free from copying errors, wouldn't that also be the "plainly apparent data" discussed in SR8?

Is the plainly apparent data a subset of the verified data free from copying errors? I think some context could be provided on what can be classified under these terms, since there may be similarities in the 2 discussed data sets.

**Comment by MatthewCurtis4** [comment]
The key distinction here and difference is that SR7 is speaking about operating the model with cleaned data while SR8 is talking about testing the model with pre-determined given data. They are two separate functions, one is for general functionality of the model without copying errors and the other is about the data given to test on.
