### ISSUE TITLE
Team 8 Review - Hazard Analysis Section 4 FMEA Table - Loss of code is more of a cause of a failure

### ISSUE THREAD

**Issue by ShrillP** [MichaelBreau/nlp-mentalhealth#84]
I would suggest that the loss of code failure mode that is currently listed would be better suited as a cause of a specific failure (e.g. the failure could be that the system that the system experiences version control issues or collaboration errors which results in a loss of code). Overall, a failure is something that prevents your system from carrying out its main functions. 
![Screen Shot 2023-10-23 at 7 46 45 PM](https://github.com/MichaelBreau/nlp-mentalhealth/assets/36174319/dad6b2b0-61c9-4305-a9ec-68fcb37ea5ce)

**Comment by MatthewCurtis4** [comment]
Changed effect of failure and added about version control issues. We kept it as general loss of code however because it is not just from version control issues, it is also the risk of losing code due to not backing up code in general.
