### ISSUE TITLE
S5 (FMEA Table) Components column does not mention components in S3(System Boundaries and Components)

### ISSUE THREAD

**Issue by rylan04** [MichaelBreau/nlp-mentalhealth#85]
The components mentioned in Section 3:
<img width="544" alt="image" src="https://github.com/MichaelBreau/nlp-mentalhealth/assets/58240299/47a0f582-ce71-4db1-9aad-79ce2e06bc8e">

Do not align with the components referenced in the FMEA table (i.e. General, Risk Prediction) making it difficult to trace hazards from the table back to the aforementioned components. It would be nice to see the components also included in the table, and if there are more then please provide a short description of the component in Section 3 to provide visibility into the root of the hazards.

**Comment by MatthewCurtis4** [comment]
Risks in our system can travel through and cover multiple of these aspects so as a result it would not make sense to sub categories them by these 4 labels, instead we thought general made more sense.
