### ISSUE TITLE
Team 8 Review - VnV Plan - Redundancy in NFR Traceability

### ISSUE THREAD

**Issue by ShrillP** [MichaelBreau/nlp-mentalhealth#99]
It is good that the tests your team wrote for your functional and non-functional requirements cover all those requirements outlined in your SRS. However, each FR and NFR is only covered by a singular test case in your VnV plan (shown below by your traceability matrices below).

![Screenshot 2023-11-06 at 2 00 33 AM](https://github.com/MichaelBreau/nlp-mentalhealth/assets/36174319/d3f49396-e19a-4cc5-adbf-a24861bbeb34)

As stated in the rubric, it may be a good idea to create some redundancy in terms of multiple tests that cover the same FR or NFR more than once. This will help ensure that not only are your FRs and NFRs are met, but also help your team build confidence in the product if all the test cases pass.

**Comment by MichaelBreau** [comment]
These were all changed.
